import { NEEDS_INPUT, type Project } from '../core/models/content.models';

/**
 * Source: PHASE-0-CONTENT-FINAL.md §6.
 *
 * All `achievements` strings are VERBATIM resume bullets. Do not paraphrase,
 * shorten or "improve" them — they are the audited content.
 *
 * `client.publicNameCleared` is false everywhere pending Vicky's contract
 * review. Flipping one flag switches the card, route slug, page title, meta
 * description, OG image and JSON-LD together.
 */
export const PROJECTS: readonly Project[] = [
  {
    slug: 'krista',
    tier: 'deep',
    client: { name: 'Krista AI', anonymized: 'Krista AI', publicNameCleared: true },
    name: 'Krista — Agentic Platform for Your Entire Enterprise',
    anonymizedName: 'Krista — Agentic Platform for Your Entire Enterprise',
    start: '2024-08',
    end: null,
    roleId: 'krista-ai',
    domain: 'Enterprise AI platform',
    summary: 'Enterprise agentic AI platform.',
    roleContext: 'Krista AI · Senior Software Engineer',
    stack: [
      'Angular 20',
      'React',
      'Node.js',
      'Python',
      'Microfrontend',
      'AWS',
      'Azure',
      'Playwright',
      'SigNoz',
      'Security',
      'AI-assisted Development',
    ],
    achievements: [
      'Owned end-to-end development of platform features across frontend and backend, from technical design through production deployment.',
      'Built and evolved scalable frontend architecture using Angular, React, TypeScript and microfrontend patterns.',
      'Developed and integrated backend APIs/services using Node.js and Python to support platform capabilities and application workflows.',
      'Designed reusable components and shared UI patterns, accelerating development across multiple projects and teams.',
      'Led migration of a production chatbot from React to Angular using AI-assisted development while maintaining architectural consistency and code quality.',
      'Implemented Playwright-based end-to-end automation testing for the Krista client application, strengthening regression coverage and release confidence.',
      'Implemented application observability using SigNoz and created dashboards to monitor application health and performance.',
      'Improved application performance and SEO, achieving 90+ Lighthouse scores across Performance, Accessibility, Best Practices and SEO.',
    ],
    metrics: [{ value: '90+', label: 'Lighthouse, all four categories', weight: 'hard' }],
    context: NEEDS_INPUT,
    challenge: NEEDS_INPUT,
    architecture: NEEDS_INPUT,
    outcome: NEEDS_INPUT,
    publicUrl: NEEDS_INPUT,
  },
  {
    slug: 'unitrax',
    tier: 'deep',
    client: {
      name: 'Unitrax',
      anonymized: 'a wealth and asset management platform provider',
      publicNameCleared: false,
    },
    name: 'Unitrax — Wealth & Asset Management / Investment Order Management Platform',
    anonymizedName: 'Wealth & Asset Management Platform',
    start: '2023-09',
    end: '2024-08',
    roleId: 'larsen-toubro',
    domain: 'Wealth & asset management',
    summary: 'Investment order management for wealth and asset management.',
    roleContext: 'Larsen and Toubro Ltd. · Full Stack Engineer',
    stack: [
      'Angular 14',
      'React',
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'Angular Material',
      'Bootstrap',
      'Node.js',
      'Jenkins',
    ],
    achievements: [
      'Optimized a data-intensive Order Management application, reducing processing errors by 30% and improving user experience by 20%.',
      'Designed and developed a data-driven Wire Order dashboard, reducing processing time by 25% and increasing user satisfaction by 15%.',
      'Established a robust library of reusable components, reducing development time by 40% and promoting code reusability.',
    ],
    metrics: [
      { value: '30%', label: 'reduction in processing errors', weight: 'hard' },
      { value: '25%', label: 'reduction in processing time', weight: 'hard' },
      { value: '40%', label: 'reduction in development time', weight: 'hard' },
      { value: '20%', label: 'enhanced user experience', weight: 'soft' },
      { value: '15%', label: 'increase in user satisfaction', weight: 'soft' },
    ],
    context: NEEDS_INPUT,
    challenge: NEEDS_INPUT,
    architecture: NEEDS_INPUT,
    outcome: NEEDS_INPUT,
    publicUrl: NEEDS_INPUT,
  },
  {
    slug: 'bosch-ministry-of-tourism',
    tier: 'card',
    client: {
      name: 'BOSCH / Ministry of Tourism (Saudi)',
      anonymized: 'a national tourism ministry',
      publicNameCleared: false,
    },
    name: 'BOSCH — Ministry of Tourism',
    anonymizedName: 'National Tourism Digital Platform',
    start: '2022-09',
    end: '2023-09',
    roleId: 'larsen-toubro',
    domain: 'Public sector / tourism',
    summary: 'National tourism digital services and administrative tooling.',
    roleContext: 'Larsen and Toubro Ltd. · Frontend Developer',
    // Supplied by the updated resume (2026-09-10); previously NEEDS INPUT.
    stack: [
      'Angular 13',
      'C#',
      '.NET',
      'SQL',
      'JavaScript',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Git',
      'Micro-Frontend',
    ],
    achievements: [
      'Led a digital initiative enhancing user experience, resulting in a 25% increase in online bookings and 20% rise in user engagement.',
      'Conceptualized and launched three e-services, revolutionizing the tourism landscape.',
      'Engineered vital administrative tools, including an admin page, dashboard, and summary page for the Ministry of Tourism (Saudi), resulting in a 40% reduction in administrative workload and a 25% improvement in user satisfaction.',
    ],
    metrics: [
      { value: '25%', label: 'increase in online bookings', weight: 'hard' },
      { value: '40%', label: 'reduction in administrative workload', weight: 'hard' },
      { value: '3', label: 'e-services launched', weight: 'hard' },
      { value: '20%', label: 'rise in user engagement', weight: 'soft' },
      { value: '25%', label: 'improvement in user satisfaction', weight: 'soft' },
    ],
    context: NEEDS_INPUT,
    challenge: NEEDS_INPUT,
    architecture: NEEDS_INPUT,
    outcome: NEEDS_INPUT,
    publicUrl: NEEDS_INPUT,
  },
  {
    slug: 'chevron-market-dataplace',
    tier: 'card',
    client: { name: 'Chevron', anonymized: 'a global energy major', publicNameCleared: false },
    name: 'Chevron — Market Dataplace',
    anonymizedName: 'Energy Sector Data Marketplace',
    start: '2022-04',
    end: '2022-07',
    roleId: 'larsen-toubro',
    domain: 'Energy / data marketplace',
    summary: 'A data marketplace connecting data producers and consumers.',
    roleContext: 'Larsen and Toubro Ltd. · Full Stack Developer',
    stack: [
      'Angular 13',
      'C#',
      '.NET',
      'SQL',
      'JavaScript',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Git',
      'Azure DevOps',
    ],
    achievements: [
      'Spearheaded the development of Data MarketPlace, facilitating seamless transactions between data producers and consumers.',
      'Independently crafted and deployed the home page for the marketplace, featuring innovative design elements and enhanced functionality.',
    ],
    metrics: [],
    context: NEEDS_INPUT,
    challenge: NEEDS_INPUT,
    architecture: NEEDS_INPUT,
    outcome: NEEDS_INPUT,
    publicUrl: NEEDS_INPUT,
  },
  {
    slug: 'eka-analytic-platform',
    tier: 'card',
    client: { name: 'EKA', anonymized: 'a commodities analytics vendor', publicNameCleared: false },
    name: 'Eka Analytics Platform',
    anonymizedName: 'Commodities Analytics Platform',
    start: '2021-09',
    end: '2022-03',
    roleId: 'larsen-toubro',
    domain: 'Market & commodities analytics',
    summary: 'An analytical tool for market and commodities analysis.',
    roleContext: 'Larsen and Toubro Ltd. · Frontend Developer',
    stack: [
      'Angular',
      'JavaScript',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Bootstrap',
      'Git',
      'Node.js',
      'Azure DevOps',
      'Azure Boards',
    ],
    achievements: [
      'Developed a data-intensive analytical platform for market and commodities analysis using Angular, TypeScript and Node.js.',
      'Established a scalable reusable component architecture to support consistent development across the platform.',
    ],
    metrics: [],
    context: NEEDS_INPUT,
    challenge: NEEDS_INPUT,
    architecture: NEEDS_INPUT,
    outcome: NEEDS_INPUT,
    publicUrl: NEEDS_INPUT,
  },
  {
    slug: 'western-union-money-transfer',
    tier: 'card',
    client: {
      name: 'Western Union',
      anonymized: 'a global money-transfer provider',
      publicNameCleared: false,
    },
    name: 'Western Union — Money Transfer App',
    anonymizedName: 'International Money Transfer App',
    start: '2020-04',
    end: '2021-04',
    roleId: 'hcl-technologies',
    domain: 'Payments / money transfer',
    summary: 'An international money transfer application.',
    roleContext: 'HCL Technologies · Frontend Developer',
    stack: [
      'Angular',
      'Figma',
      'JavaScript',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Bootstrap',
      'Git Bash',
      'JIRA',
      'Node.js',
      'Aptimise',
      'Karma & Jasmine',
      'Azure DevOps',
      'Azure Boards',
      'Jenkins',
    ],
    achievements: [
      'Played a pivotal role in enhancing functionality and user experience for international money transfers.',
      'Led the implementation efforts for key features, contributing significantly to app innovation and user engagement.',
    ],
    metrics: [],
    context: NEEDS_INPUT,
    challenge: NEEDS_INPUT,
    architecture: NEEDS_INPUT,
    outcome: NEEDS_INPUT,
    publicUrl: NEEDS_INPUT,
  },
];

/** Routes are prerendered from this list. Only deep-tier projects get a page. */
export const DEEP_PROJECT_SLUGS: readonly string[] = PROJECTS.filter((p) => p.tier === 'deep').map(
  (p) => p.slug,
);
