import type { SeoMeta } from '../core/models/content.models';
import { PROFILE } from './profile.data';

/** Source: PHASE-0-CONTENT-FINAL.md §11. */
export const SITE_NAME = 'Vicky Manora';

/** Site-wide Open Graph card, generated by tools/og/generate-og.mjs. */
export const OG_IMAGE = '/og/og-default.png';

/**
 * The card's declared shape. Facebook, LinkedIn and WhatsApp lay out the
 * large-format preview from these tags on the first scrape; without them the
 * link renders as a small thumbnail — or as plain text — until the crawler has
 * fetched and measured the file on a later pass, which for a link shared once
 * in a chat may never happen.
 *
 * These must match the bytes tools/og/generate-og.mjs emits (it screenshots at
 * exactly 1200x630 PNG); changing the generator means changing these.
 */
export const OG_IMAGE_TYPE = 'image/png';
export const OG_IMAGE_WIDTH = '1200';
export const OG_IMAGE_HEIGHT = '630';
export const OG_IMAGE_ALT =
  'Dark card reading “Vicky Manora, Senior Full Stack Engineer” over the ' +
  'site’s lattice motif, tagged Angular, React, Node.js and AWS · Azure.';

export const DEFAULT_SEO: SeoMeta = {
  title: 'Vicky Manora — Senior Full Stack Engineer',
  description: PROFILE.heroLine,
  path: '/',
  type: 'profile',
  ogImage: OG_IMAGE,
};

export const SEO_KEYWORDS: readonly string[] = [
  'Vicky Manora',
  'Senior Full Stack Engineer',
  'Angular',
  'React',
  'Node.js',
  'TypeScript',
  'AWS',
  'Azure',
];
