import type { SeoMeta } from '../core/models/content.models';
import { PROFILE } from './profile.data';

/** Source: PHASE-0-CONTENT-FINAL.md §11. */
export const SITE_NAME = 'Vicky Manora';

/** Site-wide Open Graph card, generated by tools/og/generate-og.mjs. */
export const OG_IMAGE = '/og/og-default.png';

export const DEFAULT_SEO: SeoMeta = {
  title: 'Vicky Manora — Senior Full Stack Engineer',
  description: PROFILE.heroLine,
  path: '/',
  type: 'profile',
  ogImage: OG_IMAGE,
};

export const SEO_KEYWORDS: readonly string[] = [
  'Vicky Manora',
  'Senior Full Stack Engineer',
  'Angular',
  'React',
  'Node.js',
  'TypeScript',
  'AWS',
  'Azure',
];
