// GENERATED FILE — do not edit. Regenerated by tools/generate-build-info.mjs.
export const BUILD_INFO = {
  /** ISO timestamp frozen at build time. */
  builtAt: '2026-09-10T14:25:57.306Z',
  /** Year-month the build ran, used for all duration arithmetic. */
  builtMonth: '2026-09',
} as const;
